name: test2
#on:
#  push:
#    paths:
#      - "backend/aws/**"
on:
  push:
    branches: [ sub-1 ]
  pull_request:
    branches: [ sub-1 ]
permissions:
  id-token: write
  contents: read

jobs:
#  publish-schemas:
#    strategy:
#      fail-fast: true
#      matrix:
#        account_config:
#          - aws_region: ap-northeast-1
#            aws_account: "992382697155"
#            stage: dev-jp

    #runs-on: [self-hosted, sg-kubernetes, Linux]
    env:
      AWS_ROLE_ARN: arn:aws:iam::992382697155:role/satohbkGithubOIDCRole2

    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
